include ../common.mk

# Use XeLaTeX; provide shell-escape for the minted package
LATEXMK_OPTS += -xelatex -shell-escape

all: 05-09_MCM_1.pdf 05-09_MCM_2.pdf 05-16_GIZ.pdf 05-25_Princeton.pdf
#	cp $< "$(OUT_DIR)2020-02-24 Kishimoto - Transport in IPCC AR6.pdf" || echo "::warning file=$(shell pwd)::Compile failed"
