include ../common.mk

# Use XeLaTeX; provide shell-escape for the minted package
LATEXMK_OPTS += -xelatex -shell-escape

all: 02-24_NAVIGATE.pdf
	cp $< "$(OUT_DIR)2020-02-24 Kishimoto - Transport in IPCC AR6.pdf"
