# GitHub Actions configuration to build documents from LaTeX

name: Compile

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-20.04
    container: mirisbowring/texlive_ctan_full:2019

    steps:
    - name: Check out source
      uses: actions/checkout@v2

    - name: Check out personal TeX resources
      uses: actions/checkout@v2
      with:
        repository: khaeru/tex
        path: tex
        submodules: true

    - name: Check out Google fonts
      uses: actions/checkout@v2
      with:
        repository: google/fonts
        path: fonts

    # NB can't do this, because the Docker image disables apt.
    # - name: Scan Google fonts with fontconfig
    #   run: |
    #     sudo update && sudo apt-get install -y fontconfig
    #     which fc-cache
    #     fc-cache -v fonts

    - name: Compile
      # Use personal TeX resources
      # Want to use 'env:', but the ${{ }} substitution seems to give an
      # incorrect path because the job is executed in a container.
      # env:
      #   TEXINPUTS: ".:${{ github.workspace }}/khaeru-tex//:"
      run: |
        export TEXINPUTS=.:$GITHUB_WORKSPACE/tex//:$TEXINPUTS
        export TEXFONTS=.:$GITHUB_WORKSPACE/fonts//:$TEXFONTS
        mktexlsr
        make

    - name: Upload compiled documents as a build artifact
      uses: actions/upload-artifact@v2
      with:
        name: Documents
        path: output/*
