name: Compile TeX documents

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel previous runs that have not completed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Check out source
      uses: actions/checkout@v3

    - name: Check out personal TeX resources
      uses: actions/checkout@v3
      with:
        repository: khaeru/tex
        path: tex
        submodules: true

    - name: Check out BibTeX database
      uses: actions/checkout@v3
      with:
        repository: khaeru/bibliography
        path: ref
        token: ${{ secrets.GH_PAT_REFS }}

    - name: Check out Google fonts
      uses: actions/checkout@v3
      with:
        repository: google/fonts
        path: fonts

    - name: Install packages
      run: |
        apt update
        apt install -y cabextract

    - name: Download Tahoma font
      working-directory: fonts
      # https://askubuntu.com/a/733405/141059
      # https://sourceforge.net/projects/corefonts/files/OldFiles/IELPKTH.CAB
      run: |
        pwd
        curl -O https://master.dl.sourceforge.net/project/corefonts/OldFiles/IELPKTH.CAB?viasf=1
        cabextract -F 'tahoma*ttf' IELPKTH.CAB
        ln -s tahoma.ttf Tahoma.ttf
        ln -s tahomabd.ttf "Tahoma Bold.ttf"

    - name: Scan fonts with fontconfig
      working-directory: fonts
      run: fc-cache -v .

    - name: Compile
      # Use personal TeX resources
      # Want to use 'env:', but the ${{ }} substitution seems to give an
      # incorrect path because the job is executed in a container.
      # env:
      #   TEXINPUTS: ".:${{ github.workspace }}/khaeru-tex//:"
      run: |
        export BIBINPUTS=.:$GITHUB_WORKSPACE/ref//:$BIBINPUTS
        export TEXINPUTS=.:$GITHUB_WORKSPACE/tex//:$TEXINPUTS
        export TEXFONTS=.:$GITHUB_WORKSPACE/fonts//:$TEXFONTS
        mktexlsr
        make

    - name: Upload compiled documents as a build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Documents
        path: output/*
