name: Compile TeX documents

on: [push, pull_request]

# Cancel previous runs that have not completed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Check out source
      uses: actions/checkout@v3

    - name: Check out personal TeX resources
      uses: actions/checkout@v3
      with:
        repository: khaeru/tex
        path: tex
        submodules: true

    - name: Check out BibTeX database
      uses: actions/checkout@v3
      with:
        repository: khaeru/bibliography
        path: ref

    - name: Check out Google fonts
      uses: actions/checkout@v3
      with:
        repository: google/fonts
        path: fonts

    # NB can't do this, because the Docker image disables apt.
    # - name: Scan Google fonts with fontconfig
    #   run: |
    #     sudo update && sudo apt-get install -y fontconfig
    #     which fc-cache
    #     fc-cache -v fonts

    - name: Compile
      # Use personal TeX resources
      # Want to use 'env:', but the ${{ }} substitution seems to give an
      # incorrect path because the job is executed in a container.
      # env:
      #   TEXINPUTS: ".:${{ github.workspace }}/khaeru-tex//:"
      run: |
        export BIBINPUTS=./reference:$BIBINPUTS
        export TEXINPUTS=.:$GITHUB_WORKSPACE/tex//:$TEXINPUTS
        export TEXFONTS=.:$GITHUB_WORKSPACE/fonts//:$TEXFONTS
        mktexlsr
        make

    - name: Upload compiled documents as a build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Documents
        path: output/*
